# Generated by Django 3.2.3 on 2021-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210520_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_table',
            name='shorten_url',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='url_table',
            name='url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
